# Example configuration for HCP Tester (Motor Simulator) on ESP32-C6
# Acts as the Drive to test the HCP Bridge.
#
# WIRING (ESP32-C6):
# GPIO 23 (RX) -> RS485 RO
# GPIO 22 (TX) -> RS485 DI
# GPIO 2  (DE) -> RS485 DE/RE

esphome:
  name: hcp2-tester-c6
  friendly_name: HCP2 Tester C6

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
  - platform: esphome

hcp_tester:
  id: hcp_sim
  uart_id: u0
  flow_control_pin: GPIO5

uart:
  - id: u0
    tx_pin: GPIO22
    rx_pin: GPIO23
    baud_rate: 57600
    data_bits: 8
    stop_bits: 1
    parity: EVEN

cover:
  - platform: hcp_tester
    name: "Simulated Garage Door"
    hcp_tester_id: hcp_sim

switch:
  - platform: hcp_tester
    name: "Simulated Garage Light"
    hcp_tester_id: hcp_sim
