# Example configuration for HP Core mode (Universal)
# Runs as a task on the main CPU (Core 1 on dual-core chips).
#
# WIRING (ESP32-S3):
# GPIO 18 (RX) -> RS485 RO
# GPIO 17 (TX) -> RS485 DI
# GPIO 4  (DE) -> RS485 DE/RE (Optional, set to -1 if auto-flow)

esphome:
  name: hcp2-s3-hp
  friendly_name: HCP2 S3 HP

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
  - platform: esphome

hcp_bridge:
  id: hcp_hub
  core: hp
  tx_pin: 17
  rx_pin: 18
  flow_control_pin: 4

cover:
  - platform: hcp_bridge
    name: "Garage Door"
    hcp_bridge_id: hcp_hub

switch:
  - platform: hcp_bridge
    name: "Garage Light"
    hcp_bridge_id: hcp_hub
    type: light

  - platform: hcp_bridge
    name: "Garage Vent"
    hcp_bridge_id: hcp_hub
    type: vent
