# Example configuration for HP Core mode
# Runs as a task on the main CPU.
# Works with standard Seeed Xiao RS485 board wiring (GPIO 22/23).
#
# WIRING (ESP32-C6):
# GPIO 23 (RX) -> RS485 RO
# GPIO 22 (TX) -> RS485 DI
# GPIO 2  (DE) -> RS485 DE/RE

esphome:
  name: hcp2-hp-test
  friendly_name: HCP2 HP Test

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32C6_ULP_COPROC_ENABLED: "y"
      CONFIG_ULP_COPROC_ENABLED: "y"
      CONFIG_ULP_COPROC_RESERVE_MEM: "16384"
      CONFIG_ULP_COPROC_TYPE_LP_CORE: "y"

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
  - platform: esphome

hcp_bridge:
  id: hcp_hub
  core: hp
  tx_pin: 22
  rx_pin: 23
  flow_control_pin: 2

cover:
  - platform: hcp_bridge
    name: "Garage Door"
    hcp_bridge_id: hcp_hub

switch:
  - platform: hcp_bridge
    name: "Garage Light"
    hcp_bridge_id: hcp_hub
    type: light

  - platform: hcp_bridge
    name: "Garage Vent"
    hcp_bridge_id: hcp_hub
    type: vent
