# Example configuration for HCP Tester (Motor Simulator)
# Acts as the Drive to test the HCP Bridge.
#
# WIRING (ESP32-S3):
# GPIO 18 (RX) -> RS485 RO
# GPIO 17 (TX) -> RS485 DI
# GPIO 4  (DE) -> RS485 DE/RE

esphome:
  name: hcp2-tester-s3
  friendly_name: HCP2 Tester S3

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
  - platform: esphome

hcp_tester:
  id: hcp_sim
  uart_id: u0
  flow_control_pin: 4

uart:
  - id: u0
    tx_pin: 17
    rx_pin: 18
    baud_rate: 57600
    stop_bits: 1
    parity: EVEN

cover:
  - platform: hcp_tester
    name: "Simulated Garage Door"
    hcp_tester_id: hcp_sim

switch:
  - platform: hcp_tester
    name: "Simulated Garage Light"
    hcp_tester_id: hcp_sim
