MEMORY
{
  /* LP RAM for ESP32-C6 */
  RAM (RWX) : ORIGIN = 0x50000000, LENGTH = 16K
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_STACK", RAM);

/* Define stack top for esp-lp-hal */
__stack_top = ORIGIN(RAM) + LENGTH(RAM);